dms: broadcast functionality
tloncorp/tlon-apps pull request #3535
Opened 2024-05-24 13:44 UTC by Fang-

DM "broadcasting" functionality, initially for internal-only usage. (As such, not developer for or tested on mobile, and (will be) gated on manual backend agent enabling.)

Tiny /app/broadcaster agent on the backend keeps track of established "cohorts", the actions taken on them, messages sent to them, and handles the spreading of messages into those cohorts.

Frontend has a special "broadcasts" messages filter, showing the created cohorts and letting you view the aforementioned history.

Implementation-wise, we finesse data in a couple of places to re-use existing components (most notable, pretending the cohort history is normal dm backlog), and most of the code/structure has been cargo-culted from multi-DM flows.  
I've tried to pare it down to just the bare necessities, but during review keep an eye out for things I should or should not have trimmed, or places where a different implementation pattern would be more appropriate. It's been a while since my last big frontend feature, so please be critical.

Remaining work:
- [ ] Add cohort creation flow,
- [ ] Hide broadcasts filter if backend agent not running,
- [ ] Do smaller post-change refetches,
- [ ] Maybe restructure backend json api to be slightly more normal,
- [ ] Fix bugs:
  - [ ] Don't crash on-hover of cohort messages (mb render w/ custom component instead of as fake writs),
  - [ ] Stay on messages tab when viewing a cohort,
  - [ ] Clear dialog input box after adding/removing ships from a cohort,
  - [ ] Actually render confirmation dialog prior to deleting a cohort.

2024-05-31 11:23 UTC, patosullivan requested changes
Overall, looks good. There are a few things I've flagged here. Also need to make sure this all gets formatted properly (`pnpm lint:format` if you don't have prettier in your editor).

2024-05-31 11:23 UTC, patosullivan commented on apps/tlon-web/src/components/Sidebar/MessagesSidebar.tsx
> +  });
This technically works, but it breaks our style conventions. You probably need to run prettier/the linter for all of these changes.

2024-05-31 11:23 UTC, patosullivan commented on apps/tlon-web/src/dms/BroadcastInviteDialog.tsx
> +      });
Normally all of this should live outside of the component, in this case it would probably go in state/broadcasts.

2024-05-31 11:23 UTC, patosullivan commented on apps/tlon-web/src/dms/DMOptions.tsx
> +      onClick: () => setDialog(true),
lol, thank you.

2024-05-31 11:23 UTC, patosullivan commented on apps/tlon-web/src/dms/BroadcastDm.tsx
> +export default function MultiDm() {
```suggestion
export default function BroadcastDm() {
```

2024-06-03 15:17 UTC, Fang- commented on apps/tlon-web/src/components/Sidebar/Sidebar.tsx
> +        whom=""
Yes, intentional, but I should just make that property optional here.

2024-06-03 19:30 UTC, patosullivan approved these changes
This looks good, the only thing I think is maybe missing is the ability to delete a sent broadcast (if feasible). Edit would also be nice, but we don't have edit for DMs yet.

2024-06-06 13:51 UTC, patosullivan approved these changes
Looks great, thanks for adding delete!

2024-06-21 13:36 UTC, jamesacklin commented
@latter-bolden and @arthyn, can you add your reviews? Since this is feature-flagged out I'm slightly less concerned and would like to close the milestone out.

2024-06-21 13:59 UTC, latter-bolden approved these changes
JS looks fine to me.

 I think this primarily needs a thumbs up on the hoon code before merging.

2024-06-21 13:59 UTC, latter-bolden commented on apps/tlon-web/src/dms/MessagesList.tsx
> +  console.log('filter', filter, filters.broadcasts, broadcasts.data);
```suggestion
```

2024-06-25 15:11 UTC, arthyn approved these changes
lgtm!

2024-06-25 19:28 UTC, jamesacklin commented
If we don't have any more blockers, let's merge.

2024-06-25 20:53 UTC, merged