web: activity tab using activity agent
tloncorp/tlon-apps pull request #3735
Opened 2024-07-12 16:49 UTC by arthyn

PR Checklist
- [ ] Includes changes to desk files
- [ ] Describes how you tested the PR locally (test ship vs livenet)
- [ ] If a new feature, includes automated tests
- [ ] Comments added anywhere logic may be confusing without context

2024-07-15 21:03 UTC, patosullivan requested changes
Looks good, only missing piece, I think, is rendering flagged posts/replies.

2024-07-15 21:03 UTC, patosullivan commented on apps/tlon-web/src/notifications/ActivitySummary.tsx
> +  if (relevancy === 'postToChannel') {
We'll need to cover flag-post and flag-reply cases as well

2024-07-18 16:44 UTC, Fang- reviewed
Hoon side looks good! A nit, but not a blocker.

2024-07-18 16:44 UTC, Fang- commented on desk/app/activity.hoon
> +  =*  flags  ?=(?(%flag-post %flag-reply) -<.event)
Consider `is-init` and `is-flag` for consistency and clarity. (Arguably, `is-supported` too, but that one was already there.)

2024-07-18 17:11 UTC, latter-bolden approved these changes
New virtualization stuff lgtm!

2024-07-18 18:05 UTC, jamesacklin commented
Overall looks good and matches the content on mobile.

Clicking "Mark everything as read" unfortunately results in a spinner that hangs out forever with no meaningful dojo or js-console output. Is there something else I should be inspecting to see progress there?

<img width="1609" alt="image" src="https://github.com/user-attachments/assets/8a755b13-c8ad-47ea-bb56-a90f0a9c9031">

2024-07-18 18:18 UTC, merged