group creation refurb
tloncorp/tlon-apps pull request #3928
Opened 2024-09-17 15:14 UTC by patosullivan

Fixes TLON-2714

Implements the new group/DM creation/join flow, which all starts with a single sheet now. I made sure this all works on web now, as well (by switching to using basic react state for view switching in AddGroupSheet).

Removed the FloatingAddButton since it's no longer necessary (it was only used in ChatList for triggering either the new dm or new group sheets).

Updated FloatingActionButton to match the new rounded style.

Broke `performGroupActions` out of useChannelNavigation, it now lives in useGroupActions.

Fixed an issue where the Invite Users sheet wasn't accessible from the ChatListOptions within the GroupChannels view.

Also rewrote InviteUsersSheet so that it uses the Modal component. Before this rewrite, the app would crash with a complaint about RCTView not appearing as a descendant of RCTShadowView when rendered in the EmptyChannelComponent.

2024-09-17 18:03 UTC, jamesacklin commented
Thank you! Only visual nits.

1) Let's use medium-weight (500?) for the "New Message" header and track the spacing in a bit. Also if there's a way to get all the left edges to line up, great.

![Screenshot 2024-09-17 at 1 51 46 PM](https://github.com/user-attachments/assets/2da3e993-e171-45f6-8774-cd4f358ed37f)

2) "Select Members" here is also too bold. 500 should do it.

![Simulator Screenshot - iPhone 15 Pro - 2024-09-17 at 13 52 36](https://github.com/user-attachments/assets/a9952feb-9b66-4ba9-a6d7-203a9627fe28)


3) Investigate using the Input components from the UI library. The border here will end up being much lighter and the label will be better aligned. I'm pretty sure that component will also take validator rules in case we want to simplify anything. 

The disabled button on this screen is also much too dark. We should crib from somewhere else in the app for a disabled state.

![Screenshot 2024-09-17 at 1 52 50 PM](https://github.com/user-attachments/assets/628c6ffd-17fc-4d57-a48b-861513afdf92)

The transitions between states in the sheet look OK, I think. I'm not sure we have sheet content state transitions elsewhere (group actions/admin, etc).

2024-09-17 18:56 UTC, dnbrwstr requested changes
Overall looking good; to build on James' comment above: all of this (except the actual contact list) should be doable w/ standard action sheet components/ follow the same basic structure of other action sheets. If that's not doable, I'm curious about where.

Edit: would recommend looking at `CreateChannelSheet` for reference.

2024-09-18 15:02 UTC, jamesacklin commented
I see this error when creating a group:

![image](https://github.com/user-attachments/assets/41f6dc71-f673-47b3-bc44-f3752fc3b5be)

Otherwise looks good visually.

2024-09-18 17:27 UTC, patosullivan commented
> I see this error when creating a group:
> 
> ![image](https://private-user-images.githubusercontent.com/748181/368625115-41f6dc71-f673-47b3-bc44-f3752fc3b5be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NzIwNjgsIm5iZiI6MTcyNjY3MTc2OCwicGF0aCI6Ii83NDgxODEvMzY4NjI1MTE1LTQxZjZkYzcxLWY2NzMtNDdiMy1iYzQ0LWYzNzUyZmMzYjViZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQxNTAyNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTQ3NDMyMjExMDJlYTlhMzJhN2MyYjQyMTNiNDZiZmQ1NjRmYzQ0Nzg1MDlhMDM0ZGFmMGMwZTIwY2ViYWIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RIW0aC4SP5cE3l7Iyb1AgSZoVes3nQ6Pg9qJOq7LA5Q)
> 
> Otherwise looks good visually.

this is fixed in the latest commit

2024-09-18 17:58 UTC, dnbrwstr reviewed
Nice, a couple nits here, and also:
- Horizontal margins are thicker on this sheet vs other sheets.
- Additional items should scroll under search input, not just the contact names
- iOS "new group" transition is a little wonky -- incoming views should slide over old views; right now it's doing a kind of crisscross thing (or, really, we should just open in a new screen like the other interactions do
- I'm seeing a lot of "invalid snap points" warnings

2024-09-18 18:45 UTC, patosullivan commented
> Nice, a couple nits here, and also:
> 
> * Horizontal margins are thicker on this sheet vs other sheets.
> * Additional items should scroll under search input, not just the contact names
> * iOS "new group" transition is a little wonky -- incoming views should slide over old views; right now it's doing a kind of crisscross thing (or, really, we should just open in a new screen like the other interactions do
> * I'm seeing a lot of "invalid snap points" warnings

The snap points warning is happening because I've set `snapPoints` to ['90%'] and I haven't set `snapPointsMode` to "percent". If I don't set `snapPoints` then the sheet doesn't pop up to an appropriate height:
![Simulator Screenshot - iPhone 15 - 2024-09-18 at 13 38 35](https://github.com/user-attachments/assets/8784efb4-5749-4bd5-b5ec-8dfba8ec87af)

If I do set `snapPoints` to 90% with `snapPointsMode` set to "percent", it instead takes up the whole screen (and weirdly cuts off the bottom content of the sheet):
![Simulator Screenshot - iPhone 15 - 2024-09-18 at 13 39 45](https://github.com/user-attachments/assets/07351df2-7798-43ce-8bd8-b9c4d1a4b459)

So I ended up doing what we're doing in ProfileSheet, setting snapPoints without changing the mode, which does seem to actually respect the snapPoints setting.

Which additional items are we expecting under the list of contacts?

2024-09-18 18:48 UTC, patosullivan commented on packages/app/hooks/useGroupActions.native.tsx
Not sure I understand, unless you mean we get rid of this hook and just define `performGroupActions` in the relevant controllers and pass it as a prop instead?

2024-09-18 19:11 UTC, dnbrwstr commented on packages/app/hooks/useGroupActions.native.tsx
Just that the only difference between the web and native versions are the actual `navigate` calls -- could we instead move the navigation calls to something like a useGroupNavigation hook and have a single useGroupActions hook so as not to duplicate the action parsing + data access logic?

2024-09-18 19:12 UTC, dnbrwstr commented
> Which additional items are we expecting under the list of contacts?

The idea is that the "New group" and "Join group" controls are part of the list content, so they should scroll along with the content below.

2024-09-18 20:58 UTC, dnbrwstr reviewed
Great, this is looking good. Two last bits:
- I'm still seeing the snap point warning? Could that be something on my end?
- Can "new group" open on a new screen? Or at minimum can we fix the transition so that new view slides on top of old view rather than old view sliding out to right as new view slides in from right?

2024-09-18 21:00 UTC, patosullivan commented
> Great, this is looking good. Two last bits:
> 
> * I'm still seeing the snap point warning? Could that be something on my end?
> * Can "new group" open on a new screen? Or at minimum can we fix the transition so that new view slides on top of old view rather than old view sliding out to right as new view slides in from right?

See my comments above about the snap points issue. Yeah, I can make a screen for new group.

2024-09-18 21:10 UTC, dnbrwstr commented on packages/ui/src/components/AddGroupSheet.tsx
> +      snapPoints={['90%']}
This fixes the snapPoints warning for me

```suggestion
      snapPoints={[90]}
      snapPointsMode="percent"
```

2024-09-19 14:13 UTC, dnbrwstr approved these changes
Lgtm! Appreciate the edits.

2024-09-19 14:58 UTC, merged