native: custom channel configuration
tloncorp/tlon-apps pull request #4062
Opened 2024-10-11 20:26 UTC by davidisaaclee

https://github.com/user-attachments/assets/96915597-ea2d-49e0-a211-c10482e8f7da

https://github.com/user-attachments/assets/fca5a4e2-14e1-4104-a429-95565334f00d

2024-10-18 21:13 UTC, davidisaaclee commented on packages/shared/src/api/channelContentConfig.ts
> +    // TODO: This should be validated - we'll be deserializing untrusted data
Not doing a proper validation here means that a JSON-like object with certain values could crash the app where we try to access fields on `contentConfiguration`.

(It looks like we already have `zod` pulled in due to transitive dependency of `drizzle-kit`, although I'm not sure if we're shipping `drizzle-kit` in the bundle.)

2024-10-21 16:02 UTC, davidisaaclee commented on packages/shared/src/api/channelContentConfig.ts
> +  draftInput: DraftInputId;
I'd like to make `draftInput` and `defaultPostContentRenderer` plural, but we're missing some stuff to make that happen:
- We don't have UI to change the draft input if there is more than one available (we could expand the gallery action FAB -> action sheet paradigm for this)
- I'd like to be able to say "this kind of post should be rendered with content renderer A, and this _other_ kind of post should be rendered with renderer B" – but it's not clear how to distinguish "kinds" of posts.

2024-10-21 16:03 UTC, davidisaaclee commented on packages/shared/src/api/channelContentConfig.ts
> +  draftInput: DraftInputId;
/1/chan/chat/~bitpyx-dildus/interface/msg/170141184507040415784022802543350382592

![Screenshot 2024-10-21 at 9 02 39 AM](https://github.com/user-attachments/assets/f91e4c33-2688-41e1-b9ef-3612d856efab)
![Screenshot 2024-10-21 at 9 02 52 AM](https://github.com/user-attachments/assets/47c5f978-77a2-43af-baa5-56ad1b36e655)

2024-10-21 16:08 UTC, davidisaaclee commented on packages/shared/src/api/channelContentConfig.ts
> +  draftInput: DraftInputId;
I'm not sure what form of this API we want to ship as a prototype (e.g. should we ship the structured description payload, should we namespace stuff as prototype, etc); but if we want some kind of stability here, I'd say we should change these fields to allow for plurality, but only handle values as singles:

```ts
defaultPostContentRenderers: { '*': 'tlon.r0.content.chat' },
draftInputs: ['tlon.r0.input.chat'], // or the dictionary approach i mentioned in chat above
```

2024-10-21 16:59 UTC, davidisaaclee commented
I created two demonstration PRs with custom components:
- #4090 
- #4091

2024-10-22 19:09 UTC, dnbrwstr requested changes
Awesome! Honestly looks great, and I think that this is the right level of development for starting to play with. We won't really know eg. how we want to specify channel inputs until we start trying out more template types. Also some v nice bits of cleanup in here. 

I think code looks great; the one issue that I did find was that posting to a newly created custom channel fails the first time you enter it, but works the second -- possibly related to some of the work around optimistic updates @patosullivan was doing last week.

2024-10-22 19:18 UTC, dnbrwstr commented
Oh, and noticed one other thing: currently, when there's a single gallery item on a line, the item fills the full width, doubling in size.

2024-10-22 19:36 UTC, davidisaaclee commented
> single gallery item

I think this was an existing bug – this is on Testflight:
![image](https://github.com/user-attachments/assets/7e4b16b2-d431-4127-adc0-aa7668404180)

2024-10-22 19:47 UTC, davidisaaclee commented
@dnbrwstr I can't reproduce the failure on first post that you mentioned – attached video is attempting to reproduce it, which appears to succeed. Do you have a more precise repro?

https://github.com/user-attachments/assets/3ce8b9be-82b4-456b-8b97-f441e4c01826

2024-10-22 20:08 UTC, dnbrwstr commented
Interesting, here's what I'm seeing -- it's not consistent, probably some kind of race.

https://github.com/user-attachments/assets/c6474915-bf3b-4c43-a38e-8367cb773840

2024-10-22 20:22 UTC, davidisaaclee commented
@dnbrwstr thanks, will look into it more

2024-10-22 22:06 UTC, davidisaaclee commented
@dnbrwstr I did not get a reliable repro, but I saw the bug happening relatively frequently when using a hosted account, and saw the bug correlating with an message about an unknown custom channel type `custom`. From that, I found that we were passing `channelType = custom` to `assembleNewChannelIdAndName`, which created a "nest"(?) with a `custom/` prefix, which we don't support. I don't get why this was causing a backend error, but applying [d7e49d5](https://github.com/tloncorp/tlon-apps/pull/4062/commits/d7e49d5ec41bee57145193ac3c67f369280b0f75) appears to fix the issue.

2024-10-23 11:24 UTC, patosullivan commented
> @dnbrwstr I did not get a reliable repro, but I saw the bug happening relatively frequently when using a hosted account, and saw the bug correlating with an message about an unknown custom channel type `custom`. From that, I found that we were passing `channelType = custom` to `assembleNewChannelIdAndName`, which created a "nest"(?) with a `custom/` prefix, which we don't support. I don't get why this was causing a backend error, but applying [d7e49d5](https://github.com/tloncorp/tlon-apps/pull/4062/commits/d7e49d5ec41bee57145193ac3c67f369280b0f75) appears to fix the issue.

nest is the id for the channel on the backend, and it's hardcoded to three different `kind`s, `%diary` (notebook), `%heap` (gallery), and %chat.

Types for channels live here:
https://github.com/tloncorp/tlon-apps/blob/develop/desk/sur/channels.hoon
https://github.com/tloncorp/tlon-apps/blob/develop/desk/sur/groups.hoon

For the `meta` type that we use throughout:
https://github.com/tloncorp/tlon-apps/blob/develop/desk/sur/meta.hoon

and here for dms/groupdms, but not really relevant for this:
https://github.com/tloncorp/tlon-apps/blob/develop/desk/sur/chat.hoon

Maybe we should add a new `kind` for custom channels? And/or, add new fields to `meta` (or an extension of meta for channels) for PostContentRendererId, DraftInputId, CollectionRendererId? Could still just be arbitrary strings. Seems like a better option than using the description field. cc: @Fang- @arthyn 

In general, though, I really like where this is going, it looks great.

2024-10-23 14:09 UTC, dnbrwstr approved these changes
Fix works for me, looking good! We can figure out backend stuff in the next pass.

2024-10-23 20:56 UTC, jamesacklin commented
Develop is now clean to merge into. GLHF!

2024-10-24 04:44 UTC, davidisaaclee commented
thanks,didn't mean to delay -  I was getting pumpkins ![image](https://github.com/user-attachments/assets/81fccb5d-ecb1-42f0-891f-d2327e864ae8)

2024-10-24 04:44 UTC, merged