ChatOptionsSheet: mark channel/DM/groupDM as read
tloncorp/tlon-apps pull request #4192
Opened 2024-11-17 22:06 UTC by jamesacklin

Adds a "mark as read" option to the channel actions menu, which handles channels, DMs, and group-DMs. 

Video: 

https://github.com/user-attachments/assets/1f87efe6-cfbb-449f-8fd2-bb38cd0ef107

Fixes TLON-2720

2024-11-17 22:52 UTC, latter-bolden approved these changes

2024-11-17 23:59 UTC, jamesacklin commented
@latter-bolden Expanded the scope slightly and included recursive channel unread-marking from the group options sheet.

2024-11-18 00:23 UTC, latter-bolden commented
> Expanded the scope slightly and included recursive channel unread-marking

@jamesacklin it would be simpler if we could use `markGroupRead`, did you try using that?

2024-11-18 00:28 UTC, jamesacklin commented
@latter-bolden I did. Unfortunately that works optimistically/locally, but the fact that there are unreads on child channels brings the count back when it re-queries. Open to ideas there though?

2024-11-18 00:46 UTC, latter-bolden requested changes
Blocked pending backend convo

2024-11-18 01:28 UTC, jamesacklin commented
Sweet, if it's supposed to be handled on the back-end to make the client simpler then I'm all for it.

2024-11-18 01:41 UTC, jamesacklin commented
@latter-bolden Scoped it back down. I'll open another ticket to support the same thing for all channels in a group from ChatList.

2024-11-18 01:54 UTC, merged