desktop: fix ChatList/ChannelList height/space weirdness
tloncorp/tlon-apps pull request #4223
Opened 2024-11-26 21:04 UTC by patosullivan

fixes TLON-3271

We're now using the new Text component to render text in the chat list, this fixes the line height issue that required setting a specific (larger) height for ListItem on web. Also updates the $label/l value to something less heavy (Dan's recommendation) and updates the margin/position of the overflow menu button (and the count pill next to it).

Looks much more "normal" now:
![image](https://github.com/user-attachments/assets/041255ad-de8c-4d11-a539-df34d5eeec08)

Also looks good on iOS:
![Simulator Screenshot - iPhone 15 - default - 2024-11-26 at 15 03 16](https://github.com/user-attachments/assets/d1b85c89-398a-4616-8b25-87e302d09022)

and Android:
![Screenshot_1732655065](https://github.com/user-attachments/assets/43fd72ac-710d-4d89-91f4-685c749a1a74)

2024-11-26 21:29 UTC, jamesacklin commented
Indistinguishable on mobile from the native components. Nice work!

2024-11-26 21:42 UTC, patosullivan commented
Also tacked on TLON-3279, I missed a spot w/pressables apparently.

2024-11-26 23:10 UTC, dnbrwstr requested changes
ChatList changes look good!

Let's skip the ListItem padding changes for now -- again, our lives are going to be a lot easier if we hold off on conditional rendering as much as possible until we get parity.

2024-11-27 14:12 UTC, jamesacklin approved these changes

2024-11-27 14:54 UTC, merged